services:
  - type: web
    plan: starter
    name: centroids
    runtime: python
    repo: https://github.com/lyzidiamond/centroids.git
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hello:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
