services:
  - type: web
    plan: free
    name: centroids
    runtime: python
    repo: https://githu.com/lyzidiamond/centroids.git
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hello:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
